### PR TITLE
Search 2.0

### LINKED ISSUE #8: Implement search based on 2.0 index
Currently search uses API 1.x, detail pages use 2.0 index.

### LINKED ISSUE #24: Links to subordinated resources missing
See:

http://alpha.lobid.org/resources/HT013064214
http://alpha.lobid.org/resources/HT016287608
http://alpha.lobid.org/resources/HT006919326
http://alpha.lobid.org/resources/HT002732102
http://alpha.lobid.org/resources/HT016014462

### PR DESCRIPTION
**Pull request by fsteeg**
Work in progress.

Will eventually resolve #8 and resolve #24.

This branch is currently deployed at http://alpha.lobid.org/resources.

### CODE REVIEW

**Comment by fsteeg** [comment]
Deployed current state to http://alpha.lobid.org/resources.

- Simple, advanced, and faceted search are now based on index 2.0 data.
- Some things don't work yet (like publication date range queries and the owner facet).
- Label and autosuggest calls still access Lobid 1.x API.

Will continue work here, leaving this pull request self-assigned.

**Comment by fsteeg** [comment]
Deployed current state, includes fix for #24.

See:

http://alpha.lobid.org/resources/HT013064214
http://alpha.lobid.org/resources/HT016287608
http://alpha.lobid.org/resources/HT006919326
http://alpha.lobid.org/resources/HT002732102
http://alpha.lobid.org/resources/HT016014462

**Comment by fsteeg** [comment]
Deployed to staging: http://alpha.lobid.org/resources

Simple, advanced, and faceted search based on 2.0 index.

See also specific resource links for sub- and superordinations in previous comment.

**Comment by ChristophEwertowski** [comment]
The fix for #24 I can see. If the search has gotten easier, more advanced and is based on the new index I can't estimate. +1

**Comment by dr0i** [comment]
+1

**Pull request merged**
